ALTER TABLE `arcatool`.`rcacase` ADD COLUMN created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `arcatool`.`rcacase` ADD COLUMN updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE `arcatool`.`cause` ADD COLUMN updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;