ALTER TABLE `wircatest`.`rcacase` ADD COLUMN created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE `wircatest`.`rcacase` ADD COLUMN updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE `wircatest`.`cause` ADD COLUMN updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;